const fs = require('fs');

const path = 'src/app/page.tsx';
let content = fs.readFileSync(path, 'utf8');

const oldPropsRegex = /const teacherProps = \{[\s\S]*?handleGenerateAlternative\n\s*\};/;

const newProps = `const teacherProps = {
      store, currentUser, schools,
      selectedClassId, setSelectedClassId,
      activeTab, setActiveTab,
      templateSearchQuery, setTemplateSearchQuery,
      templateSelectedSubject, setTemplateSelectedSubject,
      isUpgradeModalOpen, setIsUpgradeModalOpen,
      isProfileModalOpen, setIsProfileModalOpen,
      isAddingClass, setIsAddingClass,
      newClassName, setNewClassName,
      isAddingStudent, setIsAddingStudent,
      newStudentName, setNewStudentName,
      newStudentUsername, setNewStudentUsername,
      newStudentPassword, setNewStudentPassword,
      selectedExistingClassId, setSelectedExistingClassId,
      selectedExistingStudentId, setSelectedExistingStudentId,
      classSearch, setClassSearch,
      studentSearch, setStudentSearch,
      isImportingCSV, setIsImportingCSV,
      csvClassName, setCsvClassName,
      isCreatingAssignment, setIsCreatingAssignment,
      viewingSubmission, setViewingSubmission,
      evalScores, setEvalScores,
      evalGrade, setEvalGrade,
      evalFeedback, setEvalFeedback,
      isGradeManuallySet, setIsGradeManuallySet,
      aiInstructions, setAiInstructions,
      isAiGrading, setIsAiGrading,
      handleAiGrade,
      setEditingStudentId, setNewPasswordVal,
      setRenameTarget, setNewClassNameVal,
      setDeleteTarget,
      targetClassId, setTargetClassId,
      formatDateTime,
      renderProfileModal, renderGradebookDialog, renderTemplateCopyDialog,
      downloadAllSubmissionsZip, handleImportCSV, handleImportCSVToExisting,
      isEvaluatingPractice, setIsEvaluatingPractice,
      customCredits, setCustomCredits, toast,
      expandedSubjects, setExpandedSubjects,
      handleStartSendCopy,
      copyTargetClassId, setCopyTargetClassId,
      copyStartTime, setCopyStartTime,
      copyEndTime, setCopyEndTime,
      isSendingCopy, setIsSendingCopy,
      isEditingSettings, setIsEditingSettings,
      editStartTime, setEditStartTime,
      editEndTime, setEditEndTime,
      editIsPublicTemplate, setEditIsPublicTemplate,
      editTimeLimit, setEditTimeLimit,
      handleStartEditSettings,
      editingStudentId, newPasswordVal, isChangingPassword, setIsChangingPassword,
      deleteTarget, renameTarget, newClassNameVal,
      isGeneratingAlternative, setIsGeneratingAlternative,
      setPaymentDetails, paymentDetails,
      selectedTeacherSubject, setSelectedTeacherSubject,
      classActionType, setClassActionType,
      selectedTemplateForCopy, setSelectedTemplateForCopy,
      templateCopyClassId, setTemplateCopyClassId,
      templateCopyStartTime, setTemplateCopyStartTime,
      templateCopyEndTime, setTemplateCopyEndTime,
      templateCopyAssignType, setTemplateCopyAssignType,
      templateCopySelectedStudentIds, setTemplateCopySelectedStudentIds,
      viewingAssignment, setViewingAssignment,
      viewingAssignmentSubs, setViewingAssignmentSubs,
      setSelectedGradebookStudent, setSelectedGradebookSubject, setGradebookViewMode,
      studentActionType, setStudentActionType,
      csvFile, setCsvFile,
      csvParsingError, setCsvParsingError,
      csvImportProgress, setCsvImportProgress,
      isCustomSchoolModalOpen, setIsCustomSchoolModalOpen,
      handleAddClass, handleAddStudent, downloadCsvResults
    };`;

content = content.replace(oldPropsRegex, newProps);
fs.writeFileSync(path, content);
console.log("page.tsx teacherProps updated successfully!");
